-- MySQL Script generated by MySQL Workbench
-- 12/25/17 20:48:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cat_id`));


-- -----------------------------------------------------
-- Table `mydb`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movies` (
  `mov_id` INT NOT NULL AUTO_INCREMENT,
  `mov_title` VARCHAR(80) NOT NULL,
  `mov_cat` INT NOT NULL DEFAULT 0,
  `mov_year` INT NOT NULL DEFAULT 0000,
  `mov_info` VARCHAR(250) NULL,
  PRIMARY KEY (`mov_id`),
  INDEX `fk_mov_category_idx` (`mov_cat` ASC),
  UNIQUE INDEX `mov_info_UNIQUE` (`mov_info` ASC),
  CONSTRAINT `fk_mov_category`
    FOREIGN KEY (`mov_cat`)
    REFERENCES `mydb`.`category` (`cat_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lang` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lang` (
  `lang_id` INT NOT NULL AUTO_INCREMENT,
  `lang_name` VARCHAR(20) NOT NULL,
  `lang_abv` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`lang_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`titles` (
  `mov_id` INT NOT NULL,
  `lang` INT NOT NULL,
  `title` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`mov_id`),
  INDEX `fk_lang_langid_titles_lang_idx` (`lang` ASC),
  CONSTRAINT `fk_movies_movid_title_movid`
    FOREIGN KEY (`mov_id`)
    REFERENCES `mydb`.`movies` (`mov_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lang_langid_titles_lang`
    FOREIGN KEY (`lang`)
    REFERENCES `mydb`.`lang` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`category` (`cat_id`, `cat_name`) VALUES (0, 'other');

COMMIT;

