-- MySQL Script generated by MySQL Workbench
-- 04/09/18 12:55:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cyg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cyg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cyg` DEFAULT CHARACTER SET utf8 ;
USE `cyg` ;

-- -----------------------------------------------------
-- Table `cyg`.`mov_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cyg`.`mov_category` ;

CREATE TABLE IF NOT EXISTS `cyg`.`mov_category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cat_id`));


-- -----------------------------------------------------
-- Table `cyg`.`item_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cyg`.`item_category` ;

CREATE TABLE IF NOT EXISTS `cyg`.`item_category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyg`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cyg`.`items` ;

CREATE TABLE IF NOT EXISTS `cyg`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_title` VARCHAR(80) NOT NULL,
  `item_category` INT NOT NULL,
  `item_year` INT NOT NULL DEFAULT 0000,
  `item_info` VARCHAR(250) NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_item_cat_idx` (`item_category` ASC),
  CONSTRAINT `fk_item_cat`
    FOREIGN KEY (`item_category`)
    REFERENCES `cyg`.`item_category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyg`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cyg`.`movies` ;

CREATE TABLE IF NOT EXISTS `cyg`.`movies` (
  `mov_id` INT NOT NULL,
  `mov_cat` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`mov_id`),
  INDEX `fk_mov_category_idx` (`mov_cat` ASC),
  CONSTRAINT `fk_mov_category`
    FOREIGN KEY (`mov_cat`)
    REFERENCES `cyg`.`mov_category` (`cat_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_mov_item`
    FOREIGN KEY (`mov_id`)
    REFERENCES `cyg`.`items` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyg`.`lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cyg`.`lang` ;

CREATE TABLE IF NOT EXISTS `cyg`.`lang` (
  `lang_id` INT NOT NULL AUTO_INCREMENT,
  `lang_name` VARCHAR(20) NOT NULL,
  `lang_abv` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`lang_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyg`.`titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cyg`.`titles` ;

CREATE TABLE IF NOT EXISTS `cyg`.`titles` (
  `item_id` INT NOT NULL,
  `lang` INT NOT NULL,
  `title` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_lang_langid_titles_lang_idx` (`lang` ASC),
  CONSTRAINT `fk_movies_movid_title_movid`
    FOREIGN KEY (`item_id`)
    REFERENCES `cyg`.`movies` (`mov_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lang_langid_titles_lang`
    FOREIGN KEY (`lang`)
    REFERENCES `cyg`.`lang` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cyg`.`mov_category`
-- -----------------------------------------------------
START TRANSACTION;
USE `cyg`;
INSERT INTO `cyg`.`mov_category` (`cat_id`, `cat_name`) VALUES (1, 'other');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cyg`.`item_category`
-- -----------------------------------------------------
START TRANSACTION;
USE `cyg`;
INSERT INTO `cyg`.`item_category` (`cat_id`, `cat_name`) VALUES (1, 'Movies');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cyg`.`lang`
-- -----------------------------------------------------
START TRANSACTION;
USE `cyg`;
INSERT INTO `cyg`.`lang` (`lang_id`, `lang_name`, `lang_abv`) VALUES (1, 'English', 'en');
INSERT INTO `cyg`.`lang` (`lang_id`, `lang_name`, `lang_abv`) VALUES (2, 'Spanish', 'es');
INSERT INTO `cyg`.`lang` (`lang_id`, `lang_name`, `lang_abv`) VALUES (3, 'French', 'fr');
INSERT INTO `cyg`.`lang` (`lang_id`, `lang_name`, `lang_abv`) VALUES (4, 'Japanese', 'ja');

COMMIT;

